from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from models.report import Report, ReportStatus
from models.pipeline_run import PipelineRun
from core.files import write_artifact
import json
import uuid


async def generate_report_pdf(run_id: str, db: AsyncSession) -> Report:
    """Generate a new PDF report for a pipeline run."""
    
    # Get the pipeline run
    result = await db.execute(
        select(PipelineRun).where(PipelineRun.id == run_id)
    )
    run = result.scalar_one_or_none()
    
    if not run:
        raise ValueError(f"Pipeline run {run_id} not found")
    
    # Create new report record
    report = Report(
        run_id=run.id,
        status=ReportStatus.GENERATING
    )
    
    db.add(report)
    await db.commit()
    await db.refresh(report)
    
    try:
        # Generate mock report content
        report_content = generate_mock_report_content(run)
        
        # Save PDF artifact
        pdf_path = write_artifact(
            str(run.id),
            f"report_v{report.version}.pdf",
            report_content.encode()
        )
        
        # Update report
        report.status = ReportStatus.COMPLETED
        report.pdf_path = pdf_path
        report.sections = {
            "executive_summary": "Pipeline execution completed successfully",
            "results": "All steps executed with positive results",
            "compliance": "FDA guidelines followed"
        }
        report.compliance_flags = {
            "data_integrity": True,
            "documentation_complete": True,
            "quality_assured": True
        }
        
        await db.commit()
        return report
        
    except Exception as e:
        report.status = ReportStatus.FAILED
        await db.commit()
        raise


def generate_mock_report_content(run: PipelineRun) -> str:
    """Generate mock PDF report content."""
    return f"""
BioOS COMPUTATIONAL BIOLOGY REPORT
==================================

Pipeline: {run.name}
Target Sequence: {run.target_sequence[:50]}...
Status: {run.status}
Created: {run.created_at}

EXECUTIVE SUMMARY
This computational biology pipeline successfully analyzed the target protein
and identified promising therapeutic candidates.

METHODOLOGY
- Protein structure prediction
- Molecular docking analysis  
- ADMET property screening
- Literature validation

RESULTS
All pipeline steps completed successfully with high-confidence results.
Multiple drug candidates identified for further experimental validation.

COMPLIANCE CERTIFICATION
This analysis follows FDA guidelines for computational drug discovery.
All data has been validated and documented according to regulatory standards.

Generated by BioOS Platform
Report ID: {uuid.uuid4()}
"""